# Generated by Django 3.0.5 on 2020-07-01 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200630_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='postby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.Post'),
        ),
    ]
